version: "3.9"

services:
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   restart: unless-stopped

  # mongodb:
  #   image: mongo:7
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  productsuite-backend:
    build: .
    container_name: productsuite-backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    # depends_on:
    #   - mongodb
    #   - qdrant
    restart: unless-stopped
# volumes:
# qdrant_data:
# mongodb_data:
